version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      cooldown:
          default-days: 5
      groups:
          github-actions:
              patterns:
                  - '*'
      reviewers:
          - 'austintoddj'
      labels:
          - 'github-actions'
          - 'dependencies'
      commit-message:
          prefix: 'chore(deps)'

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      target-branch: 'develop'
      cooldown:
          default-days: 5
      groups:
          tiptap:
              patterns:
                  - '@tiptap/*'
          react-router:
              patterns:
                  - 'react-router'
                  - 'react-router-dom'
      reviewers:
          - 'austintoddj'
      labels:
          - 'npm'
          - 'dependencies'
      commit-message:
          prefix: 'chore(deps)'

    - package-ecosystem: 'composer'
      directory: '/'
      schedule:
          interval: 'weekly'
      target-branch: 'develop'
      cooldown:
          default-days: 5
      reviewers:
          - 'austintoddj'
      labels:
          - 'composer'
          - 'dependencies'
      commit-message:
          prefix: 'chore(deps)'
