-- canvas_users reshape is environment-specific (MySQL notes).
-- Do not run blindly. Build a mapping {v6_id → host users.id} first (email match is typical).
-- Full playbook: UPGRADE.md Scenario A / B.
--
-- Target v7 columns:
--   user_id (PK, unsigned bigint FK → users.id), role, username, summary, avatar,
--   website, social, locale, timezone, theme, digest, preferences, timestamps
--
-- dark_mode (v6 boolean) → theme: true → 'dark', false → 'system'
-- Drop from canvas_users: email, password, name, remember_token, deleted_at
--
-- Example sketch only (adjust types / names for your dump):
--
-- CREATE TABLE canvas_users_v7 (
--   user_id BIGINT UNSIGNED PRIMARY KEY,
--   role TINYINT NOT NULL,
--   username VARCHAR(255) NULL,
--   summary TEXT NULL,
--   avatar VARCHAR(255) NULL,
--   website VARCHAR(255) NULL,
--   social JSON NULL,
--   locale VARCHAR(255) NULL,
--   timezone VARCHAR(255) NULL,
--   theme VARCHAR(255) NULL,
--   digest TINYINT(1) NOT NULL DEFAULT 0,
--   preferences JSON NULL,
--   created_at TIMESTAMP NULL,
--   updated_at TIMESTAMP NULL,
--   CONSTRAINT canvas_users_user_id_foreign FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
-- );
--
-- INSERT INTO canvas_users_v7 (user_id, role, username, summary, avatar, locale, timezone, theme, digest, created_at, updated_at)
-- SELECT m.host_id, COALESCE(cu.role, 1), cu.username, cu.summary, cu.avatar, cu.locale,
--        'UTC', IF(cu.dark_mode = 1, 'dark', 'system'), COALESCE(cu.digest, 0), cu.created_at, cu.updated_at
-- FROM canvas_users cu
-- INNER JOIN v6_to_host_map m ON m.v6_id = cu.id
-- WHERE cu.deleted_at IS NULL;
